---
- name: Process CSV and Connect to Clients
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    csv_file_path: "test9.csv"

  tasks:
    - name: Import CSV processing tasks
      import_tasks: tasks/read_csv.yaml

    - name: Import inventory setup tasks
      import_tasks: tasks/inventory_setup.yaml

- name: Execute Ansible Tasks
  gather_facts: no
  tasks:
    - name: Import tasks from tasks/main.yaml
      import_tasks: tasks/main.yaml
      
# TODO
# 1 protocol layer 4 and layer 7
# test layer 4 and layer 7
# ICMP TESTING่่ ( ping command )
# source ip specify ว่ามาจาก ไหน
# fix hard code to variable 
# fix output to easy to read 
# check / /http /https 

# friday 


# step
# read_csv -> set inventory -> Server netcat listen -> Client -> TCP
                                                            # -> UDP
                                                            # -> ICMP
