# Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    # Build from our Dockerfile instead of pulling an image
    d.build_dir = "."
    
    # Enable SSH
    d.has_ssh = true
    
    # Expose SSH port (optional, for direct SSH access)
    d.ports = ["2223:22", "8081:80", "4445:4444"]

  end

  # Configure SSH settings
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
end
